### ISSUE TITLE
v2 Roadmap

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android-library#815]
- [ ] create all methods in v2: 
- [ ] deprecated OwncloudClient and all old Methods
- [ ] migrate all usages from OwncloudClient to NextcloudClient in files App
- [ ] check/discuss NC client creation via Factory pattern
- [ ] remove deprecated methods when switching to new major version

**Comment by ZetaTom** [comment]
# Timeline and Overview
## Progress
- overrides of `RemoteOperationResult<T> run(OwncloudClient client)`
	- initially **88** overrides (as of 30/01/2024)
	- after merging all open pull requests: **53** (as of 30/01/2024)
## Open Pull Requests
| Subject | [android-library](https://github.com/nextcloud/android-library) | [android](https://github.com/nextcloud/android) client | Tested Working? |
| ---- | ---- | ---- | :--: |
| Helpers | #1271 | no changes | ✓ |
| Comments | #1295 | no changes | ✗ |
| Sharing | #1294 | no changes | ✗ |
| DirectEditing | #1273 | nextcloud/android#12267 | ✗ |
| Notifications | #1272 | nextcloud/android#12266 | ✗ |
## To Do
### Operations Depended on WebDAV
- [ ] `CheckEtagRemoteOperation` - `PropFindMethod`
- [ ] `ChunkedFileUploadRemoteOperation` - `PropFindMethod`, `MkColMethod`, `MoveMethod`
- [ ] `CopyFileRemote Operation` - `CopyMethod`
- [ ] `CreateFolderRemoteOperation` - `MkColMethod`
- [ ] `GetTagsRemoteOperation` - `PropFindMethod`
- [ ] `LinkLivePhotoRemoteOperation` - `PropPatchMethod`
- [ ] `MarkCommentsAsReadRemoteOperation` - `PropPatchMethod`
- [ ] `MoveFileRemoteOperation` - `MoveMethod`
- [ ] `ReadFileRemoteOperation` - `PropFindMethod`
- [ ] `ReadFileVersionsRemoteOperation` - `PropFindMethod`
- [ ] `ReadFolderRemoteOperation` - `PropFindMethod`
- [ ] `ReadTrashbinFolderRemoteOperation` - `PropFindMethod`
- [ ] `RenameFileRemoteOperation` - `MoveMethod`
- [ ] `RestoreFileVersionRemoteOperation` - `MoveMethod`
- [ ] `RestoreTrashbinFileRemoteOperation` - `MoveMethod`
- [ ] `ToggleFavoriteRemoteOperation` - `PropPatchMethod`
- [ ] `ToggleFileLockRemoteOperation` - `LockMethod`, `UnlockMethod`
### List of Operations
- [ ] `CheckCurrentCredentialsOperation`
- [ ] `CheckEtagRemoteOperation`
- [ ] `CheckRemoteWipeRemoteOperation`
- [ ] `ChunkedFileUploadRemoteOperation`
- [ ] `CopyFileOperation`
- [ ] `CopyFileRemoteOperation`
- [ ] `CreateFileFromTemplateOperation`
- [ ] `CreateFolderOperation`
- [ ] `CreateFolderRemoteOperation`
- [ ] `DownloadFileOperation`
- [ ] `DownloadFileRemoteOperation`
- [ ] `FetchTemplateOperation`
- [ ] `GenerateAppPasswordRemoteOperation`
- [ ] `GetActivitiesRemoteOperation`
- [ ] `GetMetadataRemoteOperation`
- [ ] `GetTagsRemoteOperation`
- [ ] `GetUserAvatarRemoteOperation`
- [ ] `LinkLivePhotoRemoteOperation`
- [ ] `LockFileRemoteOperation`
- [ ] `MarkCommentsAsReadRemoteOperation`
- [ ] `MoveFileOperation`
- [ ] `MoveFileRemoteOperation`
- [ ] `ReadFileRemoteOperation`
- [ ] `ReadFileVersionsRemoteOperation`
- [ ] `ReadFolderRemoteOperation`
- [ ] `ReadTrashbinFolderRemoteOperation`
- [ ] `RefreshFolderOperation`
- [ ] `RemoteWipeSuccessRemoteOperation`
- [ ] `RemoveFileOperation`
- [ ] `RemoveFileRemoteOperation`
- [ ] `RemoveRemoteEncryptedFileOperation`
- [ ] `RemoveTrashbinFileRemoteOperation`
- [ ] `RenameFileOperation`
- [ ] `RenameFileRemoteOperation`
- [ ] `RestoreFileVersionRemoteOperation`
- [ ] `RestoreTrashbinFileRemoteOperation`
- [ ] `RichDocumentsCreateAssetOperation`
- [ ] `RichDocumentsUrlOperation`
- [ ] `RichWorkspaceDirectEditingRemoteOperation`
- [ ] `SearchRemoteOperation`
- [ ] `StoreMetadataRemoteOperation`
- [ ] `StoreMetadataV2RemoteOperation`
- [ ] `StreamMediaFileOperation`
- [ ] `SynchronizeFileOperation`
- [ ] `SynchronizeFolderOperation`
- [ ] `ToggleEncryptionRemoteOperation`
- [ ] `ToggleFavoriteRemoteOperation`
- [ ] `UnlockFileRemoteOperation`
- [ ] `UnlockFileV1RemoteOperation`
- [ ] `UpdateMetadataRemoteOperation`
- [ ] `UpdateMetadataV2RemoteOperation`
- [ ] `UploadFileOperation`
- [ ] `UploadFileRemoteOperation`
